version: "3"
services:
    gateway:
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - 3000:8080
        image: alexellisio/faas-gateway:latest
        networks:
        - functions
    prometheus:
        image: quay.io/prometheus/prometheus:latest
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: "-config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.memory-chunks=10000"
        ports:
            - 9090:9090
        depends_on:
            - gateway
        environment:
            no_proxy:   "gateway"
        networks:
            - functions
networks:
    functions:
        driver: overlay
        #attachable: true
